name: salla7ly
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  another_flushbar: ^1.12.30
  bloc: ^9.0.0
  cached_network_image: ^3.4.1
  cupertino_icons: ^1.0.8
  dartz: ^0.10.1
  device_preview: ^1.2.0
  dio: ^5.8.0+1
  equatable: ^2.0.7
  firebase_auth: ^5.5.3
  firebase_core: ^3.13.0
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.0
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  flutter_screenutil: ^5.9.3
  flutter_secure_storage: ^9.2.4
  fluttertoast: ^8.2.12
  freezed_annotation: ^2.4.4
  get_it: ^8.0.3
  google_fonts: ^6.2.1
  google_sign_in: ^5.4.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  image_picker: ^1.1.2
  injectable: ^2.5.0
  intl: ^0.19.0
  json_annotation: ^4.9.0
  permission_handler: ^12.0.0+1
  shimmer: ^3.0.0

dev_dependencies:
  build_runner: ^2.4.13
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^4.0.0
  injectable_generator: ^2.5.0
  freezed: ^2.5.7
  json_serializable: ^6.9.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/

flutter_intl:
  enabled: true

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/Logo.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/images/Logo.png"
    background_color: "#ffffff"
    theme_color: "#ffffff"
  windows:
    generate: true
    image_path: "assets/images/Logo.png"
    icon_size: 48
  macos:
    generate: true
    image_path: "assets/images/Logo.png"
