// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBUNdZKY1xVXH-_mwqCJ1q-_XJWsi9062E',
    appId: '1:491223251945:web:d72ee475d4858343c3e978',
    messagingSenderId: '491223251945',
    projectId: 'salla7lly-3c646',
    authDomain: 'salla7lly-3c646.firebaseapp.com',
    storageBucket: 'salla7lly-3c646.firebasestorage.app',
    measurementId: 'G-GW80BEF9YM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAoRbqDYipAcYkbb1Lo7dzOS3O6rgTJ9pA',
    appId: '1:491223251945:android:9df1e3c18d79bc75c3e978',
    messagingSenderId: '491223251945',
    projectId: 'salla7lly-3c646',
    storageBucket: 'salla7lly-3c646.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyArknc1ho_4IXtKxVlFs4ytY9vspHsd4-4',
    appId: '1:491223251945:ios:ba6499056c8be427c3e978',
    messagingSenderId: '491223251945',
    projectId: 'salla7lly-3c646',
    storageBucket: 'salla7lly-3c646.firebasestorage.app',
    iosBundleId: 'com.example.salla7ly',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyArknc1ho_4IXtKxVlFs4ytY9vspHsd4-4',
    appId: '1:491223251945:ios:ba6499056c8be427c3e978',
    messagingSenderId: '491223251945',
    projectId: 'salla7lly-3c646',
    storageBucket: 'salla7lly-3c646.firebasestorage.app',
    iosBundleId: 'com.example.salla7ly',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBUNdZKY1xVXH-_mwqCJ1q-_XJWsi9062E',
    appId: '1:491223251945:web:b610fe599c4fe098c3e978',
    messagingSenderId: '491223251945',
    projectId: 'salla7lly-3c646',
    authDomain: 'salla7lly-3c646.firebaseapp.com',
    storageBucket: 'salla7lly-3c646.firebasestorage.app',
    measurementId: 'G-K4JS7X7KLW',
  );
}
